# docker-compose.yml


services:
  db:
    image: postgres:16
    container_name: todo_project-db-1
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_project-api-tests-1
    depends_on:
      - db
    env_file:
      - .env.test
    command: ["sleep", "infinity"]

volumes:
  db_data:
