services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
      
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env
