name: Python Test
 
on: # Когда запускать?
  push: # push: при каждом пуше
    branches: [main] # в ветку main.       
  pull_request: # pull_request: когда создаётся или обновляется pull request   
    branches: [main] # в ветке main.
# Если ты работаешь в другой ветке (например, master или dev), 
# просто поменяй main на нужную.

jobs: # Что делаем? — test
  test:
    runs-on: ubuntu-latest # Где запускаем? — Виртуальная машина Ubuntu 
# (тебе не нужно устанавливать Linux, GitHub запускает всё сам на своём сервере).

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v3
# GitHub загружает твой репозиторий во временную папку на сервере.

    - name: Установить Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
# Устанавливается нужная версия Python — здесь 3.13.

    - name: Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
# Установка зависимостей — например, библиотека rich или другие, которые нужны 
# для работы твоего кода. Можно указать pip install -r requirements.txt, если 
# есть файл зависимостей.
    - name: Запустить тесты
      run: |
        python -m unittest discover -s tests
#  Запускаются юнит-тесты с помощью unittest.